djfw/admintools_bootstrap/urls.py
from django.conf.urls.defaults import *

# place app url patterns here

djfw/bugtracker/urls.py
from django.conf.urls import patterns, url
from .views import view_sync_all, found_bug

urlpatterns = patterns ('',
    url(r'^found_bug/exception/(?P<exception_id>\d+)/$', found_bug, name='found_bug_with_exception'),
    url(r'^found_bug/$', found_bug, name='found_bug'),
    url(r'^sync/all/$', view_sync_all, name='sync_all'),
)

pm/urls.py
from django.conf.urls import patterns, url
from pm.views import *

urlpatterns = patterns('',

	url(r'^$',
		index,
		name='index'
	),
	url(r'^history/(?P<another_user_id>\d+)/$',
		history,
		name='history'
	),
	url(r'^inbox/$',
		inbox,
		name='inbox'
	),
	url(r'^outbox/$',
		outbox,
		name='outbox'
	),
	url(r'^message/(?P<message_id>\d+)$',
		message_details,
		name='message_details'
	),
	url(r'^message/create/(?P<another_user_id>\d+)/$',
		message_create,
		name='message_create'
	),
	
)

tulius/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.sitemaps import views as sitemaps_views
from django.contrib import admin
from tulius.views import HomeView, StatisticsView
from django.conf import settings
from tulius import forum, gameforum
from djfw.flatpages.views import FlatpagesList
from .sitemap import sitemaps
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^sitemap.xml$', sitemaps_views.index, {'sitemaps': sitemaps, 'sitemap_url_name': 'sitemaps'}),
    url(r'^sitemap-(?P<section>.+)\.xml$', sitemaps_views.sitemap, {'sitemaps': sitemaps}, name='sitemaps'),
    
    url(r'^accounts/', include('djfw.accounts.urls')),
    url(r'^tinymce/', include('djfw.tinymce.urls',  namespace='tinymce')),
    url(r'^wysibb/', include('djfw.wysibb.urls',  namespace='wysibb')),
    url(r'^news/', include('djfw.news.urls',  namespace='news')),
    url(r'^flatpages/$', FlatpagesList.as_view(),  name='flatpages'),
    url(r'^autocomplete/', include('djfw.autocomplete.urls',  namespace='autocomplete')),
    url(r'^bugtracker/', include('djfw.bugtracker.urls',  namespace='bugtracker')),
    url(r'^profiler/', include('djfw.profiler.urls',  namespace='profiler')),
    url(r'^installer/', include('djfw.installer.urls', namespace='installer')),
    
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^statistics/$', StatisticsView.as_view(), name='stats'),

    url(r'^players/', include('tulius.players.urls', namespace='players')),
    url(r'^games/', include('tulius.games.urls',  namespace='games')),
    url(r'^forums/', include(forum.site.urls)),
    url(r'^stories/', include('tulius.stories.urls',  namespace='stories')),
    url(r'^play/', include(gameforum.site.urls)),
    
    url(r'^bugs/', include('tulius.bugs.urls',  namespace='bugs')),
    url(r'^vk/', include('tulius.vk.urls',  namespace='vk')),
    url(r'^counters/', include('tulius.counters.urls',  namespace='counters')),
)

handler404 = 'tulius.views.error404'
handler500 = 'tulius.views.error500'

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
             {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )
    urlpatterns += patterns('django.contrib.staticfiles.views',
        url(r'^static/(?P<path>.*)$', 'serve'),
    )

from djfw.installer.signals import maintaince_finished, maintaince_started
from tulius.bugs.views import maint_updated
        

def set_locale(sender, **kwargs):
    import platform
    is_windows = platform.system() == 'Windows'
    if not is_windows:
        import locale
        locale.setlocale(locale.LC_ALL, 'ru_RU.UTF-8')

maintaince_finished.connect(maint_updated)
maintaince_started.connect(set_locale)

set_locale(None)

djfw/bugtracker/forms.py
from django.utils.translation import ugettext as _
from django import forms
from .models import BugVersion, BugStatus, BugType, BugPriority, Bug, BugResolution

class CreateBugSettingform(forms.Form):
    bug_type = forms.ModelChoiceField(
        required = False,
        queryset = BugType.objects.all(),
        label = _(u'bug type'),
    )
    bug_priority = forms.ModelChoiceField(
        required = False,
        queryset = BugPriority.objects.all(),
        label = _(u'priority'),
    )
    bug_version = forms.ModelChoiceField(
        required = False,
        queryset = BugVersion.objects.filter(released=False),
        label = _(u'version'),
    )
    bug_status = forms.ModelChoiceField(
        required = False,
        queryset = BugStatus.objects.all(),
        label = _(u'status'),
    )
    
class OtherSettingsForm(forms.Form):
    resolution_status = forms.ModelChoiceField(
        required = False,
        queryset = BugStatus.objects.all(),
        label = _(u'resolution status'),
    )
    
    default_resolution = forms.ModelChoiceField(
        required = False,
        queryset = BugResolution.objects.all(),
        label = _(u'default resolution'),
    )
    
    do_bug_auto_sync  = forms.BooleanField(
        required = False,
        label = _(u'autosync bug on view'),
    )

class IssueAddCommentForm(forms.Form):
    comment = forms.CharField(
        label = _(u'comment'),
        required = False,
        widget = forms.Textarea(attrs={'class': 'mceNoEditor'}),
    )
    
class IssueAttachFileForm(IssueAddCommentForm):
    file  = forms.FileField(
        required = False,
        label = _(u'file'),
    )

class IssueResolveForm(IssueAddCommentForm):
    resolution = forms.ModelChoiceField(
        required = True,
        queryset = BugResolution.objects.all(),
        empty_label=None,
        label = _(u'resolution'),
    )

class IssueReopenForm(IssueAddCommentForm):
    pass

class FoundBugForm(forms.ModelForm):
    class Meta:
        model = Bug
        fields=('summary', 'description', )
        widgets = {
            'description': forms.Textarea(),
        }
        
class FoundbugUploadForm(forms.Form):
    file  = forms.FileField(
        required = False,
        label = _(u'attach file'),
    )

djfw/bugtracker/views.py
from django.template import loader, RequestContext
from django.http import HttpResponse, Http404
from django.conf.urls import patterns, url
from .forms import FoundBugForm, FoundbugUploadForm
import json
from .admin_views import BugsView, BugsByPriorityView, BugsByStatusView, BugsByComponentView,\
    BugsByTypeView, BugsByUserView, BugView, VersionsView, VersionView
from .core import *
from .urlizer import BugtrackerUrlizer

def known_bugs():
    version_id = get_setting( DEFAULT_VERSION_KEY)
    if not version_id:
        return None
    version = BugVersion.objects.get(id=version_id)
    return version.bugs.filter(bug__resolution_time__isnull = True).order_by('bug__priority', '-bug__create_time')
    
def view_sync_all(request):
    if not request.user.is_superuser:
        raise Http404()
    do_sync_all()
    return HttpResponse( json.dumps({'success': True}) )

def found_bug(request, exception_id=None, template_name='bugtracker/add_bug_form.haml' ):
    version_id = get_setting(DEFAULT_VERSION_KEY)
    priority_id = get_setting(DEFAULT_PRIORITY_KEY)
    type_id = get_setting(DEFAULT_BUG_TYPE_KEY)
    status_id = get_setting(DEFAULT_BUG_STATUS_KEY)
    if exception_id:
        exception_id = int(exception_id)
        try:
            from djfw.logger.models import ExceptionMessage
        except ImportError:
            from logger.models import ExceptionMessage
        return ExceptionMessage.objects.get(id=exception_id)
        exception = ExceptionMessage.objects.get(id = exception_id)
    else:
        exception = None 
    response = None
    success = False
    if (status_id and priority_id and type_id):
        if version_id:
            version = BugVersion.objects.get(id=version_id)
        priority = BugPriority.objects.get(id=priority_id)
        bug_type = BugType.objects.get(id=type_id)
        status = BugStatus.objects.get(id = status_id)
        form = FoundBugForm(data=request.POST or None)
        if not request.user.is_anonymous():
            upload_form = FoundbugUploadForm(data=request.POST or None)
        else:
            upload_form = None
        if request.method == 'POST':
            if form.is_valid():
                bug = form.save(commit=False)
                bug.bug_type = bug_type
                bug.priority = priority
                bug.status = status
                if not request.user.is_anonymous():
                    bug.reporter = request.user
                bug.environment = '*Location*:' + request.META['PATH_INFO'] 
                bug.environment += '\n*User-Agent*:' + request.META['HTTP_USER_AGENT'] 
                if 'HTTP_REFERER' in request.META: 
                    bug.environment += '\n*Referer*:' + request.META['HTTP_REFERER'] 
                bug.save()
                if exception:
                    bug_exception = BugException(bug=bug, exception_message=exception)
                    bug_exception.save()
                if version_id:
                    bug_version = VersionBug(bug=bug, version=version)
                    bug_version.save()
                if upload_form and ('file' in request.FILES):
                    uploaded_file = request.FILES['file']
                    if uploaded_file:
                        bug_file = BugUploadedFile(bug=bug)
                        bug_file.name = uploaded_file.name
                        bug_file.user = request.user
                        bug_file.save()
                        bug_file.body.save(str(bug_file.id) + '_' + bug_file.name, uploaded_file)
                success = True
        else:
            success = True
    else:
        template_name = 'bugtracker/bugtracker_not_set.haml'
    c = RequestContext(request, locals())
    t = loader.get_template(template_name)
    response = t.render(c)
    return HttpResponse( json.dumps({'success': success, 'response': response}) )

class BugAdminViews(object):
    urlizer_class = BugtrackerUrlizer
    
    def __init__(self, prefix='', app_name='admin', decorator=None, urlizer=None, base_template = 'bugtracker/base.html'):
        self.prefix = prefix
        self.decorator = None
        self.base_template = base_template
        self.app_name = app_name
        if urlizer:
            self.urlizer = urlizer(app=app_name)
        else:
            self.urlizer = self.urlizer_class(app=app_name)
            
    def decorate(self, view):
        return self.decorator(view) if self.decorator else view
    
    def read_right(self, model, user):
        return user.is_staff
    
    def write_right(self, model, user):
        if (model == IssueComment) or (model == BugUploadedFile):
            return user.is_staff
        return user.is_superuser
    
    def build_view(self, view):
        return self.decorate(
            view.as_view(
                urlizer=self.urlizer, 
                base_template=self.base_template,
                iframe=1 if self.app_name=='admin' else 0,
                viewer=self
            )
        )
    
    def get_urls(self):
        return patterns(self.prefix, 
            url(r'^main/$', self.build_view(BugsView), name='bugtracker_main'),
            url(r'^list/by_priority/(?P<pk>\d+)/$', self.build_view(BugsByPriorityView), name='bugtracker_by_priority'),
            url(r'^list/by_status/(?P<pk>\d+)/$', self.build_view(BugsByStatusView), name='bugtracker_by_status'),
            url(r'^list/by_component/(?P<pk>\d+)/$', self.build_view(BugsByComponentView), name='bugtracker_by_component'),
            url(r'^list/by_type/(?P<pk>\d+)/$', self.build_view(BugsByTypeView), name='bugtracker_by_type'),
            url(r'^list/by_user/(?P<pk>\d+)/$', self.build_view(BugsByUserView), name='bugtracker_by_user'),
            url(r'^(?P<pk>\d+)/bug/$', self.build_view(BugView), name='bugtracker_bug'),
        )

class VersionsAdminViews(BugAdminViews):
    def get_urls(self):
        return patterns(self.prefix, 
            url(r'^versions/$', self.build_view(VersionsView), name='bugtracker_versions'),
            url(r'^(.+)/version/$', self.build_view(VersionView), name='bugtracker_version'),
        )

djfw/bugtracker/templates/bugtracker/snippets/issue.html
{% load i18n %}
<table class="issue-table wide">
    <tr>
        <td width="70%">
            <table class="issue-details">
                <tr>
                    <td colspan="4">
                        <h4>{% trans "Details" %}</h4>
                    </td>
                </tr>
                <tr>
                    <td>{% trans "Type:" %}</td>
                    <td>
                        <img src="{{ issue.bug_type.icon.url }}" />
                        {{ issue.bug_type.name }}
                    </td>
                    <td>{% trans "Status:" %}</td>
                    <td>
                        <img src="{{ issue.status.icon.url }}" />
                        {{ issue.status.name }}
                </tr>
                <tr>
                    <td>{% trans "Priority:" %}</td>
                    <td>
                        <div style="color: {{ issue.priority.status_color }};">
                            <img src="{{ issue.priority.icon.url }}" />
                            {{ issue.priority.name }}
                        </div>
                    </td>
                    <td>{% trans "Resolution:" %}</td>
                    <td>
                        {% if issue.resolution %}
                            {{ issue.resolution.name }}
                        {% else %}
                            {% trans "No" %}
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td>{% trans "Version:" %}</td>
                    <td>
                        {% for version in issue.versions.all %}
                            {% include "bugtracker/snippets/issue/version_icon.html" with version=version.version %}
                            {{ version.version.name }}
                        {% endfor %}
                    </td>
                    <td>{% trans "To fix:" %}</td>
                    <td>
                        {% for version in issue.fix_versions.all %}
                            {% include "bugtracker/snippets/issue/version_icon.html" with version=version.version  %}
                            {{ version.version.name }}
                        {% endfor %}
                    </td>
                </tr>
                <tr>
                    <td>{% trans "Components:" %}</td>
                    <td colspan="3">
                        {% for component in issue.components.all %}
                            <img class="inline small-icon" src="{{ STATIC_URL }}bugtracker/img/version_archieved.png" />
                            {{ component.component.name }}
                        {% endfor %}
                    </td>
                </tr>
                {% if issue.environment %}
                    <tr>
                        <td>{% trans "Environment:" %}</td>
                        <td colspan="3">
                            {{ issue.environment|linebreaks }}
                        </td>
                    </tr>
                {% endif %}
                {% if issue.exceptions.all %}
                    <tr>
                        <td>{% trans "Exceptions:" %}</td>
                        <td colspan="3">
                            <table>
                                {% for exception in issue.exceptions.all %}
                                    <tr>
                                        <td>
                                            <a href="{{ exception.exception_message.get_absolute_url }}">
                                                {{ exception.exception_message }}
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </table>
                        </td>
                    </tr>
                {% endif %}
                {% if issue.files.all or issue.attachments.all %}
                    <tr>
                        <td colspan="4">
                            <h4>{% trans "Files:" %}</h4>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="4">
                            {% include "bugtracker/snippets/issue/files.html" %}
                        </td>
                    </tr>
                {% endif %}
                {% if issue.subtask.all %}
                    <tr>
                        <td colspan="4">
                            <h4>{% trans "Subtasks" %}</h4>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="4">
                            {% include "bugtracker/snippets/issue/subtasks.html" %}
                        </td>
                    </tr>
                {% endif %}
                {% if issue.outward_links.all or issue.inward_links.all %} 
                    <tr>
                        <td colspan="4">
                            <h4>{% trans "Links" %}</h4>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="4">
                            {% include "bugtracker/snippets/issue/links.html" %}
                        </td>
                    </tr>
                {% endif %}
                <tr>
                    <td colspan="4">
                        <h4>{% trans "Description" %}</h4>
                    </td>
                </tr>
                <tr>
                    <td colspan="4">{{ issue.description|safe|linebreaks }}</td>
                </tr>
                <tr>
                    <td colspan="4">
                        <h4>{% trans "Comments" %}</h4>
                    </td>
                </tr>
                <tr>
                    <td colspan="4">
                        {% include "bugtracker/snippets/issue/comments.html" %}
                    </td>
                </tr>
            </table>
        </td>
        <td>
            <table class="issue-right-panel">
                <tr>
                    <td colspan="2">
                        <h4>{% trans "People" %}</h4>
                    </td>
                </tr>
                <tr>
                    <td>{% trans "Assignee:" %}</td>
                    <td>
                        {% with jira_user=issue.assignee %}
                            {% if jira_user.small_icon.url %}
                                <img src="{{ jira_user.small_icon.url }}" />
                            {% endif %}
                            {% include "bugtracker/snippets/issue/jira_user.html" %}
                        {% endwith %}
                    </td>
                </tr>
                <tr>
                    <td>{% trans "Author:" %}</td>
                    <td>
                        {% if issue.reporter %}
                            <a href="{{ issue.reporter.get_absolute_url }}">
                                {{ issue.reporter }}
                            </a>
                        {% else %}
                            {% if issue.jira_reporter %}
                                {% with jira_user=issue.jira_reporter %}
                                    {% if jira_user.small_icon.url %}
                                        <img src="{{ jira_user.small_icon.url }}" />
                                    {% endif %}
                                    {% include "bugtracker/snippets/issue/jira_user.html" %}
                                {% endwith %}
                            {% endif %}
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <h4>{% trans "Dates" %}</h4>
                    </td>
                </tr>
                <tr>
                    <td>{% trans "Created:" %}</td>
                    <td>{{ issue.create_time }}</td>
                </tr>
                <tr>
                    <td>{% trans "Updated:" %}</td>
                    <td>{{ issue.updated_time }}</td>
                </tr>
                {% if issue.resolution_time %}
                    <tr>
                        <td>{% trans "Resolved:" %}</td>
                        <td>{{ issue.resolution_time }}</td>
                    </tr>
                {% endif %}
                <tr>
                    <td colspan="2">
                        <h4>{% trans "Actions" %}</h4>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        {% include "bugtracker/snippets/issue/actions.html" %}
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

djfw/bugtracker/templates/bugtracker/snippets/statistics.html
{% load i18n %}
{% load url from future %}

{% load bugtracker %}

<table class="wide" style="align: top">
    <tr>
        <td width="50%">
            <table class="bugtable">
                <tr>
                    <td class="header-td" colspan="3">
                        <h4>{% trans "Not solved:" %} {% trans "by priority"%}</h4>
                    </td>
                </tr>
                {% for priority in statistics.priorites %}
                    {% if priority.not_solved.count %}
                        <tr> 
                            <td>
                                <img src="{{ priority.icon.url }}" />
                                <a {% if iframe %}target="_parent" {%endif%}href="{% bug_by_priority priority.id %}" style="color: {{priority.status_color}};">
                                    {{ priority.name }}
                                </a>
                            </td>
                            <td>{{ priority.not_solved.count }}</td>
                            <td>
                                <div class="progressbar progress-striped bug_bar" style="width: {{ priority.not_solved_percent }}px">
                                    <div class="bar"></div>
                                </div>
                               {{ priority.not_solved_percent }}%
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
                <tr>
                    <td class="header-td" colspan="3">
                        <h4>{% trans "Not solved:"%} {% trans "by assignee"%} </h4>
                    </td>
                </tr>
                {% for jira_user in statistics.jira_users %}
                    {% if jira_user.not_solved.count %}
                        <tr>
                            <td>
                                {% if jira_user.small_icon %}
                                    <img src="{{ jira_user.small_icon.url }}" />
                                {% endif %}
                                {% if jira_user.user %}
                                    <a {% if iframe %}target="_parent" {%endif%}href="{% bug_by_user jira_user.id %}">
                                        {{ jira_user }}
                                    </a>
                                {% else %}
                                    {{ jira_user }}
                                {% endif %}
                            </td>
                            <td>
                                <a href="{{ jira_user.get_bugs_url }}">
                                    {{ jira_user.not_solved.count }}
                                </a>
                            </td>
                            <td>
                                <div class="progressbar progress-striped bug_bar" style="width: {{ jira_user.not_solved_percent }}px">
                                    <div class="bar"></div>
                                </div>
                                {{ jira_user.not_solved_percent }}%
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
                <tr>
                    <td class="header-td" colspan="3">
                        <h4>{% trans "Not solved:"%} {% trans "by version"%}</td>
                    </td>
                </tr>
                {% for version in statistics.versions %}
                    {% if version.not_solved.count %}
                        <tr class="version-row">
                            <td>
                                <a {% if iframe %}target="_parent" {%endif%}href="{% bug_version_url version.id %}">
                                    {% include "bugtracker/snippets/issue/version_icon.html" %}
                                    {{ version.name }}
                                </a>
                            </td>
                            <td>{{ version.not_solved.count }}</td>
                        </tr>
                    {% endif %}
                {% endfor %}
                {% if write_right %}
                    <tr>
                        <td class="header-td" colspan="3">
                            <h4>{% trans "Sync:" %}</h4>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="3">
                            <a class="bugtracker-sync-link" href="" url="{% url "bugtracker:sync_all" %}" 
                                wait_text="{% trans "Wait..." %}" error_text="{% trans "Error occured during sync" %}"
                                success_text="{% trans "Success!" %}" text_container="#sync_all_result">
                                <img class="inline small-icon" src="{{ STATIC_URL }}bugtracker/img/sync.png" />
                                {% trans "Sync all data" %}
                            </a>
                            <span id="sync_all_result" class="sync_results"></span>
                        </td>
                    </tr>
                {% endif %}
            </table>
        </td>
        <td>
            <table class="bugtable">
                <tr>
                    <td class="header-td" colspan="3">
                        <h4>{% trans "By status:"%}</h4>
                    </td>
                </tr>
                {% for status in statistics.statuses %}
                    {% if status.bugs.count %}
                        <tr>
                            <td>
                                <img src="{{ status.icon.url }}" />
                                <a {% if iframe %}target="_parent" {%endif%}href="{% bug_by_status status.id %}">
                                    {{ status.name }}
                                </a>
                            </td>
                            <td>{{ status.bugs.count }}</td>
                            <td>
                                <div class="progressbar progress-striped bug_bar" style="width: {{ status.bug_percent }}px">
                                    <div class="bar"></div>
                                </div>
                                {{ status.bug_percent }}%
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
                <tr>
                    <td class="header-td" colspan="3">
                        <h4>{% trans "Not solved:"%} {% trans "by component"%}</h4>
                    </td>
                </tr>
                {% for component in statistics.components %}
                    {% if component.not_solved.count %}
                        <tr>
                            <td>
                                <a {% if iframe %}target="_parent" {%endif%}href="{% bug_by_component component.id %}">
                                    <img class="inline small-icon" src="{{ STATIC_URL }}bugtracker/img/version_archieved.png" />
                                    {{ component.name }}
                                </a>
                            </td>
                            <td>{{ component.not_solved.count }}</td>
                            <td></td>
                        </tr>
                    {% endif %}
                {% endfor %}
                <tr>
                    <td class="header-td" colspan="3">
                        <h4>{% trans "Not solved:"%} {% trans "by type"%}</h4>
                    </td>
                </tr>
                {% for bug_type in statistics.bug_types %}
                    {% if bug_type.not_solved.count %}
                        <tr>
                            <td>
                                <img src="{{ bug_type.icon.url }}" />
                                <a {% if iframe %}target="_parent" {%endif%}href="{% bug_by_type bug_type.id %}">
                                    {{ bug_type.name }}
                                </a>
                            </td>
                            <td>{{ bug_type.not_solved.count }}</td>
                            <td>
                                <div class="progressbar progress-striped bug_bar" style="width: {{ bug_type.not_solved_percent }}px" >
                                    <div class="bar"></div>
                                </div>
                                {{ bug_type.not_solved_percent }}%
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
            </table>
        </td>
    </tr>
</table>