djfw/admintools_bootstrap/urls.py
from django.conf.urls.defaults import *

# place app url patterns here

djfw/tinymce/urls.py
from django.conf.urls import patterns, url
from .views import *

urlpatterns = patterns('',
    url(r'^$', Smiles.as_view(), name='index'),
    url(r'^emotions/emotions.htm$', Smiles.as_view(), name='smiles'),
    url(r'^uploaded_files/$', Uploaded_files.as_view(), name='uploaded_files'),
    url(r'^upload_file/$', Upload_file.as_view(), name='upload_file'),
)

pm/urls.py
from django.conf.urls import patterns, url
from pm.views import *

urlpatterns = patterns('',

	url(r'^$',
		index,
		name='index'
	),
	url(r'^history/(?P<another_user_id>\d+)/$',
		history,
		name='history'
	),
	url(r'^inbox/$',
		inbox,
		name='inbox'
	),
	url(r'^outbox/$',
		outbox,
		name='outbox'
	),
	url(r'^message/(?P<message_id>\d+)$',
		message_details,
		name='message_details'
	),
	url(r'^message/create/(?P<another_user_id>\d+)/$',
		message_create,
		name='message_create'
	),
	
)

tulius/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.sitemaps import views as sitemaps_views
from django.contrib import admin
from tulius.views import HomeView, StatisticsView
from django.conf import settings
from tulius import forum, gameforum
from djfw.flatpages.views import FlatpagesList
from .sitemap import sitemaps
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^sitemap.xml$', sitemaps_views.index, {'sitemaps': sitemaps, 'sitemap_url_name': 'sitemaps'}),
    url(r'^sitemap-(?P<section>.+)\.xml$', sitemaps_views.sitemap, {'sitemaps': sitemaps}, name='sitemaps'),
    
    url(r'^accounts/', include('djfw.accounts.urls')),
    url(r'^tinymce/', include('djfw.tinymce.urls',  namespace='tinymce')),
    url(r'^wysibb/', include('djfw.wysibb.urls',  namespace='wysibb')),
    url(r'^news/', include('djfw.news.urls',  namespace='news')),
    url(r'^flatpages/$', FlatpagesList.as_view(),  name='flatpages'),
    url(r'^autocomplete/', include('djfw.autocomplete.urls',  namespace='autocomplete')),
    url(r'^bugtracker/', include('djfw.bugtracker.urls',  namespace='bugtracker')),
    url(r'^profiler/', include('djfw.profiler.urls',  namespace='profiler')),
    url(r'^installer/', include('djfw.installer.urls', namespace='installer')),
    
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^statistics/$', StatisticsView.as_view(), name='stats'),

    url(r'^players/', include('tulius.players.urls', namespace='players')),
    url(r'^games/', include('tulius.games.urls',  namespace='games')),
    url(r'^forums/', include(forum.site.urls)),
    url(r'^stories/', include('tulius.stories.urls',  namespace='stories')),
    url(r'^play/', include(gameforum.site.urls)),
    
    url(r'^bugs/', include('tulius.bugs.urls',  namespace='bugs')),
    url(r'^vk/', include('tulius.vk.urls',  namespace='vk')),
    url(r'^counters/', include('tulius.counters.urls',  namespace='counters')),
)

handler404 = 'tulius.views.error404'
handler500 = 'tulius.views.error500'

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
             {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )
    urlpatterns += patterns('django.contrib.staticfiles.views',
        url(r'^static/(?P<path>.*)$', 'serve'),
    )

from djfw.installer.signals import maintaince_finished, maintaince_started
from tulius.bugs.views import maint_updated
        

def set_locale(sender, **kwargs):
    import platform
    is_windows = platform.system() == 'Windows'
    if not is_windows:
        import locale
        locale.setlocale(locale.LC_ALL, 'ru_RU.UTF-8')

maintaince_finished.connect(maint_updated)
maintaince_started.connect(set_locale)

set_locale(None)

djfw/tinymce/models.py
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.db import models
import os

class Emotion(models.Model):
    """
    Editor emotion
    """
    class Meta:
        verbose_name = _('emotion')
        verbose_name_plural = _('emotions')
    
    name = models.CharField(
        max_length=500, 
        unique=False, 
        verbose_name=_('name')
    )
    
    text = models.CharField(
        max_length=500, 
        unique=False, 
        verbose_name=_('text')
    )
    
    filename = models.CharField(
        max_length=500, 
        unique=False, 
        verbose_name=_('filename')
    )

    def __unicode__(self):
        return self.name
    
class FileUpload(models.Model):
    """
    Editor uploaded files
    """
    class Meta:
        verbose_name = _('uploaded file')
        verbose_name_plural = _('uploaded files')
        ordering = ('-id', )
        
    filename = models.CharField(
        max_length=500, 
        unique=False, 
        verbose_name=_('filename')
    )

    body = models.FileField(
        upload_to='tinymce/uploaded_files/',
        verbose_name=_('body'),
    )
    
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        null=True,
        blank=True,
        related_name='tinymce_uploads', 
        verbose_name=_('user')
    )
    
    created_at = models.DateTimeField(
        auto_now_add    = True,
        verbose_name    = _('created at'),
    )
    
    mime = models.CharField(
        max_length=500, 
        unique=False, 
        verbose_name=_('mime type'),
        null=False,
        blank=True,
        default=''
    )

    file_length = models.IntegerField(
        default=0,
        verbose_name=_(u'file length'),
    )
    
    def is_image(self):
        return (self.mime[0:5] == 'image')
    
    def __unicode__(self):
        return self.filename

    def preview_image_url(self):
        if not self.body:
            return None
        if self.is_image():
            image_path = os.path.join(settings.MEDIA_URL, self.body.url)
        else:
            image_path = os.path.join(settings.STATIC_URL, 'tinymce/img/box_address.png')
        return '<img src="'+ str(image_path) +'" style="max-height: 85px; max-width: 85px"/>'
    
    def get_absolute_url(self):
        return self.body.url if self.body else None
        
    def file_size(self):
        from django.template.defaultfilters import filesizeformat
        return filesizeformat(self.file_length)
    
    get_absolute_url.short_description = _('URL')
    preview_image_url.short_description = _('image')
    file_size.short_description = _('file length')
    preview_image_url.allow_tags = True
    

djfw/tinymce/views.py
from django.views.generic import TemplateView, View
from django.http import Http404
from django.conf import settings
from django.db import transaction
from mimetypes import guess_type
from djfw.uploader import handle_upload
from .models import Emotion, FileUpload
import json

class Smiles(TemplateView):
    template_name='tinymce/smiles/tiny_mce_smiles.haml'
    
    def get_context_data(self, **kwargs):
        emotions = Emotion.objects.all()
        if not emotions:
            path = settings.STATIC_ROOT + '/tinymce/list.json'
            f = open(path, 'r')
            emotions_list = json.load(f)
            with transaction.commit_on_success():
                for emotion in emotions_list:
                    emotion_obj = Emotion(name=emotion['name'], text=emotion['text'], filename=emotion['filename']) 
                    emotion_obj.save()
            emotions = Emotion.objects.all()
        emotions_list = {}
        new_emotions = []
        for emotion in emotions:
            if not (emotion.filename in emotions_list):
                emotions_list[emotion.filename] = emotion
                new_emotions += [emotion]
        emotions = []
        for i in xrange(0, len(new_emotions)/10 + 1):
            emotions += [new_emotions[10*i:10*i+10]]
        return {'emotions': emotions}

class Uploaded_files(TemplateView):
    template_name='tinymce/plugins/file_upload.haml'
    
    def get_context_data(self, **kwargs):
        if not self.request.user.is_anonymous():
            all_files = FileUpload.objects.filter(user=self.request.user).order_by('-id')[:15]
            all_files = [afile for afile in all_files if afile.body]
        else:
            all_files = []
        files = []
        for i in xrange(0, len(all_files)/5 + 1):
            files += [all_files[5*i:5*i+5]]
        return {'files': files}

def save_upload(request, upload, filename):
    uploaded_file = FileUpload(user=request.user, filename=filename, 
        file_length=len(upload), mime=guess_type(filename, True)[0])
    if uploaded_file.mime is None:
        uploaded_file.mime = ''
    uploaded_file.save()
    uploaded_file.body.save(str(uploaded_file.pk) + '_' +filename, upload)
    uploaded_file.save()
    return {'url': uploaded_file.body.url, 
            'filename': uploaded_file.filename, 
            'image': uploaded_file.is_image(),}

class Upload_file(View):
    def post(self, request, *args, **kwargs):
        if request.user.is_staff:
            return handle_upload(request, save_upload)
        else:
            raise Http404()

djfw/tinymce/templates/tinymce/advanced_editor.html
{% load tinymce_config %}
{% load url from future %}

<script type="text/javascript">
    tinyMCE.init({
        base_dj_url: "{% url 'tinymce:index' %}",
        gecko_spellcheck:true,
        mode : "textareas",
        editor_deselector : "mceNoEditor",
        theme: 'advanced',
        language : 'ru',
        plugins : "table, paste, emotions, file_upload",
        theme_advanced_toolbar_location: 'top',
        theme_advanced_toolbar_align: 'left',
        theme_advanced_buttons1 : 
            "formatselect, separator, "+
            "bold, italic, underline, strikethrough, separator," +
            "justifyleft, justifycenter, justifyright, justifyfull, separator," +
            "bullist, numlist, separator, outdent, indent, separator, undo, redo, separator," +
            "link, unlink, image, blockquote, separator, removeformat, separator, " +
            "forecolor, backcolor, separator, sub, sup, separator, pasteword, code",
        theme_advanced_buttons2 : "tablecontrols, separator, emotions, file_upload",
        theme_advanced_buttons3 : "",
        theme_advanced_blockformats : "p,h1,h2,h3,",
        content_css : "{% tinymce_css %}?" + new Date().getTime(),
        height : "520",
        width : "100%",
        preformatted : true,
        convert_urls : false,
        forced_root_block : '',
        force_br_newlines : false,
        force_p_newlines : false,
        keep_styles : false,
    });
</script>

djfw/tinymce/templates/tinymce/init_advanced_editor.html
{% include "tinymce/init_editor.html" %}
{% include "tinymce/advanced_editor.html" %}

djfw/tinymce/templates/tinymce/init_editor.html
{% load static %}
<script type="text/javascript" src="{% static "tinymce/jscripts/tiny_mce/tiny_mce.js" %}"></script>

djfw/tinymce/templates/tinymce/simple_editor.html
{% load url from future %}
<script type="text/javascript">
    tinyMCE.init({
        base_dj_url: "{% url 'tinymce:index' %}",
        gecko_spellcheck:true,
        mode : "textareas",
        editor_deselector : "mceNoEditor",
        language : 'ru',
        theme: 'advanced',
        plugins : "emotions,bbcode",
        theme_advanced_toolbar_location: 'top',
        theme_advanced_toolbar_align: 'left',
        theme_advanced_buttons1 : "fontsizeselect,bold,italic,underline,strikethrough, separator," +
            "undo,redo,link,unlink,image,forecolor," +
            "removeformat,cleanup,emotions, blockquote, separator, code",
        theme_advanced_buttons2 : "",
        theme_advanced_buttons3 : "",
        theme_advanced_blockformats : "p,h1,h2,h3,h4,h5,h6,",
        theme_advanced_path : false,
        theme_advanced_statusbar_location : "none",
        content_css : "{{ MEDIA_URL }}css/tinymce.css?" + new Date().getTime(),
        preformatted : true,
        forced_root_block : '',
        force_br_newlines : false,
        force_p_newlines : false,
        convert_urls : false,
        width : "100%"
    });
</script>