djfw/admintools_bootstrap/urls.py
from django.conf.urls.defaults import *

# place app url patterns here

djfw/wysibb/urls.py
from django.conf.urls import patterns, url
from .views import upload_file, upload_image

urlpatterns = patterns('',
    url(r'^upload_file/$', upload_file, name='upload_file'),
    url(r'^upload_image/$', upload_image, name='upload_image'),
)

pm/urls.py
from django.conf.urls import patterns, url
from pm.views import *

urlpatterns = patterns('',

	url(r'^$',
		index,
		name='index'
	),
	url(r'^history/(?P<another_user_id>\d+)/$',
		history,
		name='history'
	),
	url(r'^inbox/$',
		inbox,
		name='inbox'
	),
	url(r'^outbox/$',
		outbox,
		name='outbox'
	),
	url(r'^message/(?P<message_id>\d+)$',
		message_details,
		name='message_details'
	),
	url(r'^message/create/(?P<another_user_id>\d+)/$',
		message_create,
		name='message_create'
	),
	
)

tulius/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.sitemaps import views as sitemaps_views
from django.contrib import admin
from tulius.views import HomeView, StatisticsView
from django.conf import settings
from tulius import forum, gameforum
from djfw.flatpages.views import FlatpagesList
from .sitemap import sitemaps
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^sitemap.xml$', sitemaps_views.index, {'sitemaps': sitemaps, 'sitemap_url_name': 'sitemaps'}),
    url(r'^sitemap-(?P<section>.+)\.xml$', sitemaps_views.sitemap, {'sitemaps': sitemaps}, name='sitemaps'),
    
    url(r'^accounts/', include('djfw.accounts.urls')),
    url(r'^tinymce/', include('djfw.tinymce.urls',  namespace='tinymce')),
    url(r'^wysibb/', include('djfw.wysibb.urls',  namespace='wysibb')),
    url(r'^news/', include('djfw.news.urls',  namespace='news')),
    url(r'^flatpages/$', FlatpagesList.as_view(),  name='flatpages'),
    url(r'^autocomplete/', include('djfw.autocomplete.urls',  namespace='autocomplete')),
    url(r'^bugtracker/', include('djfw.bugtracker.urls',  namespace='bugtracker')),
    url(r'^profiler/', include('djfw.profiler.urls',  namespace='profiler')),
    url(r'^installer/', include('djfw.installer.urls', namespace='installer')),
    
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^statistics/$', StatisticsView.as_view(), name='stats'),

    url(r'^players/', include('tulius.players.urls', namespace='players')),
    url(r'^games/', include('tulius.games.urls',  namespace='games')),
    url(r'^forums/', include(forum.site.urls)),
    url(r'^stories/', include('tulius.stories.urls',  namespace='stories')),
    url(r'^play/', include(gameforum.site.urls)),
    
    url(r'^bugs/', include('tulius.bugs.urls',  namespace='bugs')),
    url(r'^vk/', include('tulius.vk.urls',  namespace='vk')),
    url(r'^counters/', include('tulius.counters.urls',  namespace='counters')),
)

handler404 = 'tulius.views.error404'
handler500 = 'tulius.views.error500'

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
             {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )
    urlpatterns += patterns('django.contrib.staticfiles.views',
        url(r'^static/(?P<path>.*)$', 'serve'),
    )

from djfw.installer.signals import maintaince_finished, maintaince_started
from tulius.bugs.views import maint_updated
        

def set_locale(sender, **kwargs):
    import platform
    is_windows = platform.system() == 'Windows'
    if not is_windows:
        import locale
        locale.setlocale(locale.LC_ALL, 'ru_RU.UTF-8')

maintaince_finished.connect(maint_updated)
maintaince_started.connect(set_locale)

set_locale(None)

djfw/wysibb/models.py
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.db import models

class Smile(models.Model):
    class Meta:
        verbose_name = _('smile')
        verbose_name_plural = _('smiles')
    
    name = models.CharField(
        max_length=500, 
        unique=False, 
        verbose_name=_('name')
    )
    
    text = models.CharField(
        max_length=500, 
        unique=False, 
        verbose_name=_('text')
    )
    
    image = models.ImageField(
        upload_to='wysibb/smiles/',
        verbose_name=_('image'),
    )
    
    def preview_image(self):
        if not self.image:
            return None
        return '<img src="'+ str(self.image.url) +'"/>'
    
    def __unicode__(self):
        return self.name
    
    preview_image.allow_tags = True
    preview_image.short_description = _('image')
    
class UploadedFile(models.Model):
    class Meta:
        verbose_name = _('uploaded file')
        verbose_name_plural = _('uploaded files')
        ordering = ('-id', )
        
    filename = models.CharField(
        max_length=500, 
        unique=False, 
        verbose_name=_('filename')
    )

    body = models.FileField(
        upload_to='wysibb/uploaded_files/',
        verbose_name=_('body'),
    )
    
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        null=True,
        blank=True,
        related_name='wysibb_files', 
        verbose_name=_('user')
    )
    
    created_at = models.DateTimeField(
        auto_now_add    = True,
        verbose_name    = _('create time'),
    )
    
    mime = models.CharField(
        max_length=500, 
        unique=False, 
        verbose_name=_('mime type')
    )

    file_size = models.IntegerField(
        default=0,
        verbose_name=_(u'file length'),
    )
    
    def __unicode__(self):
        return self.filename

    def get_absolute_url(self):
        return self.body.url if self.body else None
        
    def file_size_formated(self):
        from django.template.defaultfilters import filesizeformat
        return filesizeformat(self.file_size)
    
    def filename_link(self):
        if (not self.body):
            return self.filename
        return '<a href="%s">%s</a>' % (self.body.url, self.filename)

    get_absolute_url.short_description = _('URL')
    file_size_formated.short_description = _('file size')
    filename_link.allow_tags = True
    filename_link.short_description = _('File')
    
class UploadedImage(models.Model):
    """
    Uploaded images
    """
    class Meta:
        verbose_name = _('uploaded image')
        verbose_name_plural = _('uploaded images')
        ordering = ('-id', )
        
    filename = models.CharField(
        max_length=500, 
        unique=False, 
        verbose_name=_('filename')
    )

    image = models.ImageField(
        upload_to='wysibb/uploaded_image/',
        verbose_name=_('image'),
    )

    thumb = models.ImageField(
        upload_to='wysibb/uploaded_thumbs/',
        verbose_name=_('thumbnail'),
    )
    
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        null=True,
        blank=True,
        related_name='wysibb_images', 
        verbose_name=_('user')
    )
    
    created_at = models.DateTimeField(
        auto_now_add    = True,
        verbose_name    = _('create time'),
    )
    
    mime = models.CharField(
        max_length=500, 
        unique=False, 
        verbose_name=_('mime type')
    )

    file_size = models.IntegerField(
        default=0,
        verbose_name=_(u'file length'),
    )
    
    def __unicode__(self):
        return self.filename

    def preview_image(self):
        if (not self.image) or (not self.thumb):
            return ""
        return '<a href="%s"><img src="%s" style="max-height: 85px; max-width: 85px"/></a>' % (self.image.url, self.thumb.url)
    
    def get_absolute_url(self):
        return self.body.url if self.body else None
        
    def file_size_formated(self):
        from django.template.defaultfilters import filesizeformat
        return filesizeformat(self.file_size)
    
    get_absolute_url.short_description = _('URL')
    preview_image.short_description = _('image')
    file_size_formated.short_description = _('file size')
    preview_image.allow_tags = True
    

djfw/wysibb/views.py
from django.contrib.auth.decorators import login_required
from django.conf import settings
from mimetypes import guess_type
from djfw.uploader import handle_upload
from .models import UploadedFile, UploadedImage
import StringIO
from django.core.files.base import ContentFile
from trans import transliterate

try:
    from PIL import Image
except ImportError:
    import Image

def save_uploaded_file(request, upload, filename):
    filename = transliterate(filename)
    uploaded_file = UploadedFile(
        user=request.user, 
        filename=filename, 
        file_size=len(upload), 
        mime=(guess_type(filename, True)[0] or '')
    )
    uploaded_file.save()
    uploaded_file.body.save(str(uploaded_file.pk) + '_' +filename, upload)
    uploaded_file.save()
    return {'url': uploaded_file.body.url, 
            'filename': uploaded_file.filename}

@login_required
def upload_file(request):
    return handle_upload(request, save_uploaded_file)

def save_uploaded_image(request, upload, filename):
    filename = transliterate(filename)
    uploaded_file = UploadedImage(
        user=request.user, 
        filename=filename, 
        file_size=len(upload), 
        mime=(guess_type(filename, True)[0] or '')
    )
    
    uploaded_file.save()
    uploaded_file.image.save(str(uploaded_file.pk) + '_' +filename, upload)
    uploaded_file.save()
    uploaded_file.image.open('b')
    image = Image.open(uploaded_file.image)
    
    thumb_size = getattr(settings, 'WYSIBB_THUMB_SIZE', (100, 100))
    thumb_format = getattr(settings, 'WYSIBB_THUMB_FORMAT', 'png')
    image.thumbnail(thumb_size, Image.ANTIALIAS)
    
    image_content = StringIO.StringIO()
    image.save(image_content, format=thumb_format)
    image_file = ContentFile(image_content.getvalue())
    uploaded_file.thumb.save(str(uploaded_file.pk) + '_' +filename, image_file)
    return {'status': 1,
            'msg': "OK",
            'image_link': uploaded_file.image.url,
            'thumb_link': uploaded_file.thumb.url}

@login_required
def upload_image(request):
    return handle_upload(request, save_uploaded_image)

djfw/wysibb/templates/wysibb/init.html
{% load bbcodes i18n %}
{% load url from future %}
<script src="{{ STATIC_URL }}wysibb/jquery.wysibb.js"></script>
<link rel="stylesheet" href="{{ STATIC_URL }}wysibb/theme/default/wbbtheme.css" type="text/css" />

<script>

function wysibb_image_load() {
    this.$modal.find("#imguploader").dragfileupload({
        url: this.strf(this.options.img_uploadurl,this.options),
        extraParams: {
            maxwidth: this.options.img_maxwidth,
            maxheight: this.options.img_maxheight
        },
        themePrefix: this.options.themePrefix,
        themeName: this.options.themeName,
        success: $.proxy(function(data) {
            this.$txtArea.insertImage(data.image_link,data.thumb_link);
            this.closeModal();
            this.updateUI();
         },this)
    });
                
    if (!$.support.htmlSerialize) {
        //ie not posting form by security reason, show default file upload
        $.log("IE not posting form by security reason, show default file upload");
        this.$modal.find("#nicebtn").hide();
        this.$modal.find("#fileupl").css("opacity",1);
    }
                
    this.$modal.find("#fileupl").bind("change",function() {
        $("#fupform").submit();
    });
    
    this.$modal.find("#fupform").bind("submit",$.proxy(function(e) {
        $(e.target).parents("#imguploader").hide().after('<div class="loader"><img src="'+this.options.themePrefix+'/'+this.options.themeName+'/img/loader.gif" /><br/><span>'+CURLANG.loading+'</span></div>').parent().css("text-align","center");
        this.$modal.find("#fupform").ajaxSubmit({
            url: this.strf(this.options.img_uploadurl,this.options),
            success: $.proxy(function(data) {
                this.$txtArea.insertImage(data.image_link,data.thumb_link);
                this.closeModal();
                this.updateUI();
            },this),
            dataType: 'json'
        });
    },this))
}

$.fn.insertFileLink = function(fileurl,filename) {
    var editor = this.data("wbb");
    var code = editor.getCodeByCommand('link',{url:fileurl,seltext: filename})
    this.insertAtCursor(code);
    return editor;
}

function wysibb_file_load() {
    this.$modal.find("#fupfileform").ajaxSubmit({
        url: "{% url 'wysibb:upload_file' %}",
        success: $.proxy(function(data) {
            this.$txtArea.insertFileLink(data.url,data.filename);
            this.closeModal();
            this.updateUI();
        },this),
        dataType: 'json'
    });
}

var id="wysibbid";
var wbbOpt = {
    buttons:  "bold,italic,underline,strike,|,img,video,myfile,link,|,bullist,numlist,|,smilebox,|,fontcolor,fontsize,|,quote,table,removeFormat",
    smileList: [{% bbcode_smiles_list %}],
    img_uploadurl: "{% url 'wysibb:upload_image' %}",
    minheight: "100",
    allButtons: {
        myfile : {
            title: "{% trans "Add file" %}",
            buttonHTML: '<span class="fonticon ve-tlb-img1"><img src="{{ STATIC_URL }}wysibb/filebutton.gif"/></span>',
            modal: {
                title: "{% trans "Add file" %}",
                width: "600px",
                tabs: [
                    {
                        title: "",
                        html: '<form id="fupfileform" class="upload" method="post" enctype="multipart/form-data"><input id="fileupl" class="file" type="file" name="img" /></form>'
                    }
                ],
                onSubmit: wysibb_file_load,
            },
            transform : {'<a href="{URL}">{FILENAME}</a>':"[url={URL}]{FILENAME}[/url]",}
        },

    }
}

$(document).ready(function() {
    $("textarea").wysibb(wbbOpt);
});
</script>

djfw/wysibb/templates/wysibb/smiles_list.html
{% for smile in smiles %}
{title:"{{ smile.name }}", img: '<img src="{{ smile.image.url }}" class="sm">', bbcode:"{{ smile.text}}"},
{% endfor %}